
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller

# this is the pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller
      containers:
        - name: controller
          image: controller:dev
          imagePullPolicy: Never # only local image
          volumeMounts:
            - name: heartbeat
              mountPath: /tmp
          env:
            - name: TZ
              value: Europe/Berlin

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - test $(( $(date +%s) - $(stat -c %Y /tmp/heartbeat.log) )) -lt 15
            initialDelaySeconds: 30 # how long to wait after startup
            periodSeconds: 10 # frequency of executing command
            failureThreshold: 4 # default is 3
      volumes:
        - name: heartbeat
          emptyDir: {}   # shared by all containers in the pod, not visible on the host, auto deleted later
          #hostPath:
          #  path: /home/lukas/devops_practice/solar/watchdog_test/tmp/ # fix later
          #  type: DirectoryOrCreate

